Repository Gamify-IT/bugfinder, pull requests merged in 2022-07, with the labels that each got.

#10 remove actions-cleanup
  .github/workflows/deploy-docker-image-on-release.yml
  .github/workflows/sonarqube-build.yml
  .github/workflows/test.yml
Labels: bug

#9 Select multiple bugs and read codes/solutions from json file
  src/App.vue
  src/components/CodeBox.vue
  src/dummy/codes.json
  src/dummy/solution.json
  src/models/bugfindergame.ts
  src/models/code-visualizer.ts
  src/models/models.ts
  src/views/FinishView.vue
  src/views/GameView.vue
  src/views/HomeView.vue
  tests/unit/bugfindergame.spec.ts
  tsconfig.json
Labels: feature

#11 Add test coverage on sonarqube for bugfinder
  .github/workflows/sonarqube-build.yml
Labels: feature

#12 production route on container
  .nginx/nginx.conf
Labels: bug

#13 Add error type selection and fixing
  package-lock.json
  package.json
  src/components/CodeBox.vue
  src/dummy/codes.json
  src/dummy/solution.json
  src/main.ts
  src/models/bugfindergame.ts
  src/models/code-feedback.ts
  src/models/code-visualizer.ts
  src/models/models.ts
  src/views/GameView.vue
  tests/unit/code-feedback.spec.ts
Labels: feature

#15 Create some tests for CodeBox
  jest.config.js
  src/components/CodeBox.vue
  tests/unit/CodeBox.spec.ts
Labels: feature

#16 add chat colors
  package.json
  src/components/ChatBox.vue
  src/models/chat.ts
  src/models/models.ts
  src/views/GameView.vue
Labels: feature

#19 refactoring to prepare for pr review
  package-lock.json
  src/components/ChatBox.vue
  src/components/CodeBox.vue
  src/components/SelectBugModal.vue
  src/components/WordBox.vue
  src/models/code.ts
  src/services/bugfindergame.ts
  src/services/chat.ts
  src/services/code-feedback.ts
  src/services/code-visualizer.ts
  src/views/GameView.vue
  tests/unit/CodeBox.spec.ts
  tests/unit/bugfindergame.spec.ts
  tests/unit/code-feedback.spec.ts
  tests/unit/code-visualizer.spec.ts
Labels: maintenance
