Repository Gamify-IT/bugfinder, pull requests merged in 2022-06, with the labels that each got.

#1 Created ts classes for game logic and create jest tests for bugfindergame class
  .eslintrc.js
  .nginx/nginx.conf
  .prettierrc.json
  Dockerfile
  jest.config.js
  package-lock.json
  package.json
  src/App.vue
  src/components/CodeBox.vue
  src/components/HelloWorld.vue
  src/main.ts
  src/model/bugfindergame.ts
  src/model/models.ts
  src/store/index.ts
  tests/unit/bugfindergame.spec.ts
  tsconfig.json
Labels: feature

#2 create basic frontend
  package-lock.json
  package.json
  src/App.vue
  src/assets/base.css
  src/assets/logo.png
  src/main.ts
  src/views/GameView.vue
  src/views/HomeView.vue
Labels: feature

#4 create an information-rich Readme
  README.md
Labels: documentation

#5 improve the frontend and gameplay
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/App.vue
  src/assets/avatar.svg
  src/components/ChatBox.vue
  src/components/CodeBox.vue
  src/models/bugfindergame.ts
  src/models/code-visualizer.ts
  src/models/models.ts
  src/views/FinishView.vue
  src/views/GameView.vue
  src/views/HomeView.vue
  tests/unit/bugfindergame.spec.ts
Labels: feature

#7 fix deployment uri
  README.md
  src/App.vue
  src/assets/base.css
  vue.config.js
Labels: bug
